###
POST http://localhost:8000/users
Content-Type: application/json

{
    "firstName": "João Vitorooo",
    "lastName": "Matos Gouveia",
    "email": "joaovitormatosgouveia@gmail.com",
    "password": "admin"
}

###
GET http://localhost:8000/users

###
PATCH  http://localhost:8000/users/65da2cc0265976d11621993e
Content-Type: application/json

{
    "firstName": "Joãoo Viterrrrrr",
    "lastName": "Matos Gouveiaaaa"
}

###
DELETE  http://localhost:8000/users/65da2cc0265976d11621993e